# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CD

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: create .env
      run: |
        touch .env
        echo DATABASE_URL=${{ secrets.DATABASE }} >> .env
        echo ACCESS_TOKEN_SECRET=${{ secrets.ACCESS_TOKEN_SECRET }} >> .env
        ls -a
        mkdir tmp
    - name: build docker image
      run: |
        docker build . --tag ghcr.io/039-098-103/backend
        docker images
    - name: push docker image to registry
      run: |
        docker push ghcr.io/039-098-103/backend

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            export CR_PAT=${{ secrets.GITHUB_TOKEN }}
            echo $CR_PAT | docker login ghcr.io -u zyict --password-stdin
            docker pull ghcr.io/039-098-103/backend
            docker images
            docker rm -f backend
            docker run -d --name backend --network bagshop --ip 172.18.0.5 ghcr.io/039-098-103/backend